/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bimbelkita;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author asus
 */
final class Guru_Form extends javax.swing.JFrame {

    File file;
    JFileChooser jfc;
    private DefaultTableModel tabmode;
    private DefaultComboBoxModel combolist;
    private ResultSet hasil;

    CRUDguru crud = new CRUDguru();

    Connection con = new koneksi().con();

    /**
     * Creates new form Guru_Form
     */
    public Guru_Form() {
        initComponents();
        tampil_database();
        tampilBidangStudi();
        cekAngka();
        setLocationRelativeTo(this);
        txt_id.setVisible(false);
        txt_namaPhoto.setVisible(false);
    }

    public void tampil_database() {
        Object[] baris = {"ID", "NIP", "Nama", "Bidang", "kelamin", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_guru.setModel(tabmode);
        try {
            crud.setBidangStudi(combo_bidangStudi.getSelectedIndex());
            hasil = crud.tampilData(crud.getbidangStudi());
            while (hasil.next()) {
                crud.setID(hasil.getString("guru_id"));
                crud.setNip(hasil.getInt("nip"));
                crud.setNama(hasil.getString("nama"));
                crud.setBidang(hasil.getString("bidang"));
                crud.setKelamin(hasil.getString("kelamin"));
                crud.setAlamat(hasil.getString("alamat"));
                crud.setTanggal_Lahir(hasil.getDate("tanggal_lahir"));
                String tgl = crud.getTanggal_Lahir().toString();
                String nis = String.valueOf(crud.getNip());
                String[] data = {crud.getID(), nis, crud.getNama(), crud.getBidang(), crud.getKelamin(), crud.getAlamat(), tgl};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void cekAngka() {
        txt_nip.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent ke) {
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyCode() == 8 || ke.getKeyCode() == 46) {
                    txt_nip.setEditable(true);
                } else {
                    txt_nip.setEditable(false);
                }
            }
        });
    }

    public void tampilBidangStudi() {
        String[] bidangStudi = {"Bhs. Indonesia", "Bhs. Inggris", "Matematika", "IPA", "IPS"};
        combolist = new DefaultComboBoxModel(bidangStudi);
        combo_bidangStudi.setModel(combolist);
        crud.setBidangStudi(combo_bidangStudi.getSelectedIndex());
    }

    public void reset_text() {
        txt_nip.setText(null);
        combo_bidangStudi.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        txt_ttl.setDate(null);
        txt_nama.setText(null);
        txt_alamat.setText(null);
        txt_namaPhoto.setText(null);
        label_photo.setIcon(null);
        txt_id.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nip = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        radio_L = new javax.swing.JRadioButton();
        radio_P = new javax.swing.JRadioButton();
        txt_ttl = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_guru = new javax.swing.JTable();
        btn_insert = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        label_photo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_namaPhoto = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        combo_bidangStudi = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_siswa = new javax.swing.JMenuItem();
        menu_guru = new javax.swing.JMenuItem();
        menu_kelas = new javax.swing.JMenuItem();
        menu_jadwal = new javax.swing.JMenuItem();
        menu_ruang = new javax.swing.JMenuItem();
        menu_keluar = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Guru");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bidang Studi");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kelamin");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Lahir");

        buttonGroup1.add(radio_L);
        radio_L.setForeground(new java.awt.Color(255, 255, 255));
        radio_L.setText("Laki - Laki");

        buttonGroup1.add(radio_P);
        radio_P.setForeground(new java.awt.Color(255, 255, 255));
        radio_P.setText("Perempuan");

        tabel_guru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_guruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_guru);

        btn_insert.setText("INSERT");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_keluar.setText("KELUAR");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PENCARIAN");

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });

        btn_cari.setText("CARI");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        label_photo.setBackground(new java.awt.Color(255, 255, 255));
        label_photo.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        label_photo.setText("      Pilih Foto");
        label_photo.setOpaque(true);
        label_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_photoMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FORM GURU");

        txt_namaPhoto.setEditable(false);

        combo_bidangStudi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_bidangStudi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_bidangStudiItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(60, 60, 60))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_cari)
                                .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(txt_namaPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nip, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txt_nama)
                            .addComponent(combo_bidangStudi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_alamat)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radio_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(radio_P))
                            .addComponent(txt_ttl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_insert)
                                .addGap(57, 57, 57)
                                .addComponent(btn_reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(btn_update)
                                .addGap(68, 68, 68)
                                .addComponent(btn_delete)
                                .addGap(72, 72, 72)
                                .addComponent(btn_keluar))
                            .addComponent(jScrollPane2))))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(radio_L)
                            .addComponent(radio_P))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(combo_bidangStudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_ttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_insert)
                            .addComponent(btn_reset)
                            .addComponent(btn_update)
                            .addComponent(btn_delete)
                            .addComponent(btn_keluar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_namaPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cari)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        menu_siswa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_siswa.setText("Form Siswa");
        menu_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_siswaActionPerformed(evt);
            }
        });
        jMenu1.add(menu_siswa);

        menu_guru.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menu_guru.setText("Form Guru");
        menu_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guruActionPerformed(evt);
            }
        });
        jMenu1.add(menu_guru);

        menu_kelas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menu_kelas.setText("Form Kelas");
        menu_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kelasActionPerformed(evt);
            }
        });
        jMenu1.add(menu_kelas);

        menu_jadwal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menu_jadwal.setText("Form Jadwal");
        menu_jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jadwalActionPerformed(evt);
            }
        });
        jMenu1.add(menu_jadwal);

        menu_ruang.setText("Form Ruang");
        menu_ruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ruangActionPerformed(evt);
            }
        });
        jMenu1.add(menu_ruang);

        jMenuBar1.add(jMenu1);

        menu_keluar.setText("Keluar");
        menu_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keluarMouseClicked(evt);
            }
        });
        menu_keluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menu_keluarKeyPressed(evt);
            }
        });
        jMenuBar1.add(menu_keluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        if (txt_nip.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nip belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nama belum diisi !");
            txt_id.requestFocus();
        } else if (combo_bidangStudi.equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, bidang studi belum diisi !");
            txt_id.requestFocus();
        } else if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, kelamin belum diisi !");
            txt_id.requestFocus();
        } else if (txt_alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, alamat belum diisi !");
            txt_id.requestFocus();
        } else if (txt_ttl.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, tanggal lahir belum diisi !");
            txt_id.requestFocus();
        } else if (file == null) {
            JOptionPane.showMessageDialog(null, "Maaf, foto belum diisi !");
            label_photo.requestFocus();
        } else {
            try {
                int nip = Integer.parseInt(txt_nip.getText());
                String nama = txt_nama.getText();
                String bidang = combo_bidangStudi.getSelectedItem().toString();
                String kelamin = null;

                if (radio_L.isSelected()) {
                    kelamin = "L";
                } else if (radio_P.isSelected()) {
                    kelamin = "P";
                }
                String alamat = txt_alamat.getText();
                SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
                String tanggal_lahir = String.valueOf(tgl.format(txt_ttl.getDate()));
                String filename = file.toString();
                String extensi = FilenameUtils.getExtension(filename);
                String foto = UUID.randomUUID().toString() + "." + extensi;
                crud.setNama(nama);
                crud.setNip(nip);
                crud.setBidang(bidang);
                crud.setAlamat(alamat);
                crud.setKelamin(kelamin);
                crud.simpanData(nip, nip, nama, bidang, kelamin, alamat, tanggal_lahir, foto);
                try {
                    String path = new File(".").getCanonicalPath();
                    String movePath = path + "/img/guru/" + foto;
                    FileUtils.copyFile(
                            FileUtils.getFile(file),
                            FileUtils.getFile(movePath));

                } catch (IOException ex) {
                    Logger.getLogger(Siswa_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                tampil_database();
                reset_text();
            } catch (NumberFormatException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (txt_nip.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nip belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nama belum diisi !");
            txt_id.requestFocus();
        } else if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, kelamin belum diisi !");
            txt_id.requestFocus();
        } else if (txt_alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, alamat belum diisi !");
            txt_id.requestFocus();
        } else if (txt_ttl.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, tanggal lahir belum diisi !");
            txt_id.requestFocus();
        } else {
            try {
                int id = Integer.parseInt(txt_id.getText());
                int nip = Integer.parseInt(txt_nip.getText());
                String nama = txt_nama.getText();
                String kelamin = null;

                if (radio_L.isSelected()) {
                    kelamin = "L";
                } else if (radio_P.isSelected()) {
                    kelamin = "P";
                }
                String alamat = txt_alamat.getText();
                SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
                String tanggal_lahir = String.valueOf(tgl.format(txt_ttl.getDate()));
                String filename = file.toString();
                String extensi = FilenameUtils.getExtension(filename);
                String foto = UUID.randomUUID().toString() + "." + extensi;
                hasil = crud.fotoGuru(txt_id.getText());
                while (hasil.next()) {
                    crud.setFoto(hasil.getString("foto"));
                }
                String bidang = combo_bidangStudi.getSelectedItem().toString();
                String oldFoto = crud.getFoto();
                crud.setNama(nama);
                crud.setNip(nip);
                crud.setBidang(bidang);
                crud.setAlamat(alamat);
                crud.setKelamin(kelamin);
                crud.ubahData(id, nip, nama, bidang, kelamin, alamat, tanggal_lahir, foto);

                try {
                    String path = new File(".").getCanonicalPath();
                    String movePath = path + "/img/guru/" + foto;
                    FileUtils.copyFile(
                            FileUtils.getFile(file),
                            FileUtils.getFile(movePath));
                    FileUtils.deleteQuietly(new File(path + "/img/guru/" + oldFoto));

                } catch (IOException ex) {
                    Logger.getLogger(Siswa_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                reset_text();
                tampil_database();
            } catch (NumberFormatException e) {
                System.out.println(e);
            } catch (SQLException ex) {
                Logger.getLogger(Siswa_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if (txt_id.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID belum diisi !");
            txt_id.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ? ", "  Warning", 2) == JOptionPane.YES_OPTION) {
                String id = "";
                try {
                    crud.setID(txt_id.getText());
                    crud.hapusData(crud.getID());
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?", "Warning", 2)
                == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        Object[] baris = {"ID", "NIP", "Nama", "Bidang", "kelamin", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_guru.setModel(tabmode);
        try {
            crud.setBidangStudi(combo_bidangStudi.getSelectedIndex());
            crud.setKeyword(txt_cari.getText());
            hasil = crud.searchData(crud.getKeyword(), crud.getbidangStudi());

            while (hasil.next()) {
                crud.setID(hasil.getString("guru_id"));
                crud.setNip(hasil.getInt("nip"));
                crud.setNama(hasil.getString("nama"));
                crud.setBidang(hasil.getString("Bidang"));
                crud.setKelamin(hasil.getString("kelamin"));
                crud.setAlamat(hasil.getString("alamat"));
                crud.setTanggal_Lahir(hasil.getDate("tanggal_lahir"));
                String tgl = crud.getTanggal_Lahir().toString();
                String nip = String.valueOf(crud.getNip());
                String bidang = String.valueOf(crud.getBidang());
                String[] data = {crud.getID(), nip, crud.getNama(), bidang, crud.getKelamin(), crud.getAlamat(), tgl};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txt_cariCaretUpdate

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        Object[] baris = {"ID", "NIP", "Nama", "Bidang", "kelamin", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_guru.setModel(tabmode);
        try {
            crud.setBidangStudi(combo_bidangStudi.getSelectedIndex());
            crud.setKeyword(txt_cari.getText());
            hasil = crud.searchData(crud.getKeyword(), crud.getbidangStudi());

            while (hasil.next()) {
                crud.setID(hasil.getString("guru_id"));
                crud.setNip(hasil.getInt("nip"));
                crud.setNama(hasil.getString("nama"));
                crud.setBidang(hasil.getString("Bidang"));
                crud.setKelamin(hasil.getString("kelamin"));
                crud.setAlamat(hasil.getString("alamat"));
                crud.setTanggal_Lahir(hasil.getDate("tanggal_lahir"));
                String tgl = crud.getTanggal_Lahir().toString();
                String nip = String.valueOf(crud.getNip());
                String bidang = String.valueOf(crud.getBidang());
                String[] data = {crud.getID(), nip, crud.getNama(), bidang, crud.getKelamin(), crud.getAlamat(), tgl};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void label_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_photoMouseClicked
        jfc = new JFileChooser();
        if (jfc.showOpenDialog(label_photo) == JFileChooser.APPROVE_OPTION) {

            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image image = toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized = image.getScaledInstance(150, 200, Image.SCALE_DEFAULT);
            ImageIcon imageIcon = new ImageIcon(imagedResized);
            label_photo.setText(null);
            label_photo.setIcon(imageIcon);
            txt_namaPhoto.setText(jfc.getSelectedFile().getName());
            txt_namaPhoto.show();
            file = new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_label_photoMouseClicked

    private void tabel_guruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_guruMouseClicked
        label_photo.setText("                 Pilih Foto");
        label_photo.setIcon(null);
        txt_namaPhoto.setText(null);
        try {
            int row = tabel_guru.rowAtPoint(evt.getPoint());
            String id = tabel_guru.getValueAt(row, 0).toString();
            String nip = tabel_guru.getValueAt(row, 1).toString();
            String nama = tabel_guru.getValueAt(row, 2).toString();
            String bidang = tabel_guru.getValueAt(row, 3).toString();
            String kelamin = tabel_guru.getValueAt(row, 4).toString();
            String alamat = tabel_guru.getValueAt(row, 5).toString();
            Date tgl = null;
            String tanggal_lahir = tabel_guru.getValueAt(row, 6).toString();
            tgl = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(tanggal_lahir);
            hasil = crud.fotoGuru(id);
            while (hasil.next()) {
                crud.setFoto(hasil.getString("foto"));
            }
            String foto = crud.getFoto();
            String path = new File(".").getCanonicalPath();
            System.out.println(path);
            System.out.println(foto);
            BufferedImage img = null;
            img = ImageIO.read(new File(path + "/img/guru/" + foto));
            System.out.println(img);
            Image imagedResized = img.getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(imagedResized);
            label_photo.setText(null);
            label_photo.setIcon(imageIcon);
            System.out.println(id);
            txt_id.setText(String.valueOf(id));
            txt_nip.setText(String.valueOf(nip));
            txt_nama.setText(String.valueOf(nama));
            crud.setBidangIndex(String.valueOf(bidang));
            combo_bidangStudi.setSelectedIndex(crud.getBidangIndex());
            txt_namaPhoto.setText(foto);
            txt_namaPhoto.show();
            if ("L".equals(kelamin)) {
                radio_L.setSelected(true);
            } else if ("P".equals(kelamin)) {
                radio_P.setSelected(true);
            }
            txt_alamat.setText(String.valueOf(alamat));
            txt_ttl.setDate(tgl);
        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_tabel_guruMouseClicked

    private void menu_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_siswaActionPerformed
        this.dispose();
        Siswa_Form sf = new Siswa_Form();
        sf.show();
    }//GEN-LAST:event_menu_siswaActionPerformed

    private void combo_bidangStudiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_bidangStudiItemStateChanged
        tampil_database();
    }//GEN-LAST:event_combo_bidangStudiItemStateChanged

    private void menu_ruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ruangActionPerformed
        this.dispose();
        Ruang_Form rf = new Ruang_Form();
        rf.show();
    }//GEN-LAST:event_menu_ruangActionPerformed

    private void menu_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_guruActionPerformed

    private void menu_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_kelasActionPerformed
        this.dispose();
        Kelas_Form kf = new Kelas_Form();
        kf.show();
    }//GEN-LAST:event_menu_kelasActionPerformed

    private void menu_jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jadwalActionPerformed
        this.dispose();
        jadwal_form jf = new jadwal_form();
        jf.show();
    }//GEN-LAST:event_menu_jadwalActionPerformed

    private void menu_keluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menu_keluarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_keluarKeyPressed

    private void menu_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keluarMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?", "Warning", 2)
                == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menu_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guru_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combo_bidangStudi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_photo;
    private javax.swing.JMenuItem menu_guru;
    private javax.swing.JMenuItem menu_jadwal;
    private javax.swing.JMenuItem menu_kelas;
    private javax.swing.JMenu menu_keluar;
    private javax.swing.JMenuItem menu_ruang;
    private javax.swing.JMenuItem menu_siswa;
    private javax.swing.JRadioButton radio_L;
    private javax.swing.JRadioButton radio_P;
    private javax.swing.JTable tabel_guru;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_namaPhoto;
    private javax.swing.JTextField txt_nip;
    private com.toedter.calendar.JDateChooser txt_ttl;
    // End of variables declaration//GEN-END:variables
}
