/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bimbelkita;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author asus
 */
public final class Siswa_Form extends javax.swing.JFrame {

    File file;
    JFileChooser jfc;
    private DefaultTableModel tabmode;
    private DefaultComboBoxModel combolist;
    private ResultSet hasil;
    /**
     * Creates new form Siswa_Form
     */
    CRUDsiswa crud = new CRUDsiswa();
    Session s = new Session();
    Connection con = new koneksi().con();

    public Siswa_Form() {
        initComponents();
        tampilKelas();
        tampil_database();
        setLocationRelativeTo(this);
        txt_id.setVisible(false);
        txt_namaPhoto.setVisible(false);
        cekAngka();
    }

    public void tampil_database() {
        Object[] baris = {"ID", "NIS", "Nama", "kelas", "kelamin", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_siswa.setModel(tabmode);
        try {
            hasil = crud.tampilData();
            while (hasil.next()) {
                crud.setID(hasil.getString("siswa_id"));
                crud.setNis(hasil.getInt("nis"));
                crud.setNama(hasil.getString("nama"));
                crud.setKelas(hasil.getInt("kelas"));
                crud.setKelamin(hasil.getString("kelamin"));
                crud.setAlamat(hasil.getString("alamat"));
                crud.setTanggal_Lahir(hasil.getDate("tanggal_lahir"));
                String tgl = crud.getTanggal_Lahir().toString();
                String nis = String.valueOf(crud.getNis());
                String kelas = String.valueOf(crud.getKelas());
                String[] data = {crud.getID(), nis, crud.getNama(), kelas, crud.getKelamin(), crud.getAlamat(), tgl};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {

        }
    }

    public void tampilKelas() {

        String[] kelas = {"7", "8", "9"};
        combolist = new DefaultComboBoxModel(kelas);
        combobox_kelas.setModel(combolist);
    }

    public void reset_text() {
        txt_nis.setText("");
        combobox_kelas.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        txt_tanggal.setDate(null);
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_namaPhoto.setText(null);
        label_photo.setIcon(null);
        label_photo.setText("         Pilih Foto");
    }

    public void cekAngka() {
        txt_nis.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent ke) {
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyCode() == 8 || ke.getKeyCode() == 46) {
                    txt_nis.setEditable(true);
                } else {
                    txt_nis.setEditable(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_siswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nis = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_siswa = new javax.swing.JTable();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        radio_L = new javax.swing.JRadioButton();
        radio_P = new javax.swing.JRadioButton();
        btn_insert = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        btn_keluar = new javax.swing.JButton();
        label_photo = new javax.swing.JLabel();
        txt_namaPhoto = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        combobox_kelas = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menu_siswa = new javax.swing.JMenuItem();
        menu_guru = new javax.swing.JMenuItem();
        menu_kelas = new javax.swing.JMenuItem();
        menu_jadwal = new javax.swing.JMenuItem();
        menu_ruang = new javax.swing.JMenuItem();
        menu_keluar = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));

        panel_siswa.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kelas");

        txt_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nisActionPerformed(evt);
            }
        });

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_siswa);

        buttonGroup1.add(radio_L);
        radio_L.setForeground(new java.awt.Color(255, 255, 255));
        radio_L.setText("Laki - laki");
        radio_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_LActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_P);
        radio_P.setForeground(new java.awt.Color(255, 255, 255));
        radio_P.setText("Perempuan");
        radio_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_PActionPerformed(evt);
            }
        });

        btn_insert.setText("INSERT");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        btn_keluar.setText("KELUAR");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        label_photo.setBackground(java.awt.Color.white);
        label_photo.setFont(new java.awt.Font("Stencil", 2, 14)); // NOI18N
        label_photo.setText("         Pilih Foto");
        label_photo.setAlignmentX(0.5F);
        label_photo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_photo.setMaximumSize(new java.awt.Dimension(150, 200));
        label_photo.setMinimumSize(new java.awt.Dimension(150, 200));
        label_photo.setOpaque(true);
        label_photo.setPreferredSize(new java.awt.Dimension(150, 200));
        label_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_photoMouseClicked(evt);
            }
        });

        txt_namaPhoto.setEditable(false);
        txt_namaPhoto.setMaximumSize(new java.awt.Dimension(150, 30));
        txt_namaPhoto.setMinimumSize(new java.awt.Dimension(150, 30));
        txt_namaPhoto.setPreferredSize(new java.awt.Dimension(150, 30));
        txt_namaPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaPhotoActionPerformed(evt);
            }
        });

        btn_cari.setText("CARI");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Pencarian");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM SISWA");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kelamin");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alamat");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal Lahir");

        combobox_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_siswaLayout = new javax.swing.GroupLayout(panel_siswa);
        panel_siswa.setLayout(panel_siswaLayout);
        panel_siswaLayout.setHorizontalGroup(
            panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_siswaLayout.createSequentialGroup()
                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_siswaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(62, 62, 62))
                    .addGroup(panel_siswaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_namaPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_cari, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_cari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_siswaLayout.createSequentialGroup()
                        .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_siswaLayout.createSequentialGroup()
                                .addComponent(btn_insert)
                                .addGap(73, 73, 73)
                                .addComponent(btn_reset)
                                .addGap(82, 82, 82)
                                .addComponent(btn_update)
                                .addGap(83, 83, 83)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(btn_keluar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_siswaLayout.createSequentialGroup()
                                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nis)
                                    .addComponent(txt_nama)
                                    .addComponent(combobox_kelas, 0, 162, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(49, 49, 49)
                                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_siswaLayout.createSequentialGroup()
                                        .addComponent(radio_L, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(radio_P, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_tanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(40, 40, 40))
                    .addGroup(panel_siswaLayout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_siswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(376, 376, 376))
        );
        panel_siswaLayout.setVerticalGroup(
            panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_siswaLayout.createSequentialGroup()
                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_siswaLayout.createSequentialGroup()
                        .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_siswaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radio_P)
                                        .addComponent(radio_L))))
                            .addGroup(panel_siswaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(18, 18, 18)
                        .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(20, 20, 20)
                        .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel11)
                                .addComponent(combobox_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_siswaLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(label_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_namaPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_delete)
                    .addComponent(btn_keluar)
                    .addComponent(btn_reset)
                    .addGroup(panel_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_insert)
                        .addComponent(btn_cari))
                    .addComponent(btn_update))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        menu.setText("Menu");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        menu_siswa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_siswa.setText("Form Siswa");
        menu_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_siswaActionPerformed(evt);
            }
        });
        menu.add(menu_siswa);

        menu_guru.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menu_guru.setText("Form Guru");
        menu_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guruActionPerformed(evt);
            }
        });
        menu.add(menu_guru);

        menu_kelas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menu_kelas.setText("Form Kelas");
        menu_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kelasActionPerformed(evt);
            }
        });
        menu.add(menu_kelas);

        menu_jadwal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menu_jadwal.setText("Form Jadwal");
        menu_jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jadwalActionPerformed(evt);
            }
        });
        menu.add(menu_jadwal);

        menu_ruang.setText("Form  Ruang");
        menu_ruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ruangActionPerformed(evt);
            }
        });
        menu.add(menu_ruang);

        jMenuBar1.add(menu);

        menu_keluar.setText("Keluar");
        menu_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_keluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_siswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?", "Warning", 2)
                == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (txt_nis.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nis belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nama belum diisi !");
            txt_id.requestFocus();
        } else if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, kelamin belum diisi !");
            txt_id.requestFocus();
        } else if (txt_alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, alamat belum diisi !");
            txt_id.requestFocus();
        } else if (txt_tanggal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, tanggal lahir belum diisi !");
            txt_id.requestFocus();
        } else {
            try {
                int id = Integer.parseInt(txt_id.getText());
                int nis = Integer.parseInt(txt_nis.getText());
                String nama = txt_nama.getText();
                int kelas = Integer.parseInt(combobox_kelas.getSelectedItem().toString());
                String kelamin = null;

                if (radio_L.isSelected()) {
                    kelamin = "L";
                } else if (radio_P.isSelected()) {
                    kelamin = "P";
                }
                String alamat = txt_alamat.getText();
                SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
                String tanggal_lahir = String.valueOf(tgl.format(txt_tanggal.getDate()));
                String filename = file.toString();
                String extensi = FilenameUtils.getExtension(filename);
                String foto = UUID.randomUUID().toString() + "." + extensi;
                hasil = crud.fotoSiswa(txt_id.getText());
                while (hasil.next()) {
                    crud.setFoto(hasil.getString("foto"));
                }
                String oldFoto = crud.getFoto();

                crud.setNama(nama);
                crud.setNis(nis);
                crud.setKelas(kelas);
                crud.setAlamat(alamat);
                crud.setKelamin(kelamin);
                crud.ubahData(id, nis, nama, kelas, kelamin, alamat, tanggal_lahir, foto);

                try {
                    String path = new File(".").getCanonicalPath();
                    String movePath = path + "/img/siswa/" + foto;
                    FileUtils.copyFile(
                            FileUtils.getFile(file),
                            FileUtils.getFile(movePath));
                    FileUtils.deleteQuietly(new File(path + "/img/siswa/" + oldFoto));

                } catch (IOException ex) {
                    Logger.getLogger(Siswa_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                reset_text();
                tampil_database();
            } catch (NumberFormatException e) {
                System.out.println(e);
            } catch (SQLException ex) {
                Logger.getLogger(Siswa_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        if (txt_nis.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nis belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nama belum diisi !");
            txt_id.requestFocus();
        } else if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, kelamin belum diisi !");
            txt_id.requestFocus();
        } else if (txt_alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, alamat belum diisi !");
            txt_id.requestFocus();
        } else if (txt_tanggal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Maaf, tanggal lahir belum diisi !");
            txt_id.requestFocus();
        } else {
            try {
                int nis = Integer.parseInt(txt_nis.getText());
                String nama = txt_nama.getText();
                int kelas = 7;
                kelas = Integer.parseInt(combobox_kelas.getSelectedItem().toString());
                String kelamin = null;
                if (radio_L.isSelected()) {
                    kelamin = "L";
                } else if (radio_P.isSelected()) {
                    kelamin = "P";
                }

                String alamat = txt_alamat.getText();
                SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
                String tanggal_lahir = String.valueOf(tgl.format(txt_tanggal.getDate()));
                String filename = file.toString();
                String extensi = FilenameUtils.getExtension(filename);
                String foto = UUID.randomUUID().toString() + "." + extensi;
                crud.setkelasId(kelas);
                int kelasId = crud.getKelasId();
                crud.simpanData(nis, nis, nama, kelas, kelamin, alamat, tanggal_lahir, foto, kelasId);

                try {
                    String path = new File(".").getCanonicalPath();
                    String movePath = path + "/img/siswa/" + foto;
                    FileUtils.copyFile(
                            FileUtils.getFile(file),
                            FileUtils.getFile(movePath));

                } catch (IOException ex) {
                    Logger.getLogger(Siswa_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                tampil_database();
                reset_text();
            } catch (NumberFormatException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void radio_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_PActionPerformed

    private void radio_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_LActionPerformed

    private void tabel_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_siswaMouseClicked
        label_photo.setText("                 Pilih Foto");
        label_photo.setIcon(null);
        txt_namaPhoto.setText(null);
        try {
            int row = tabel_siswa.rowAtPoint(evt.getPoint());
            String id = tabel_siswa.getValueAt(row, 0).toString();
            String nis = tabel_siswa.getValueAt(row, 1).toString();
            String nama = tabel_siswa.getValueAt(row, 2).toString();
            String kelas = tabel_siswa.getValueAt(row, 3).toString();
            String kelamin = tabel_siswa.getValueAt(row, 4).toString();
            String alamat = tabel_siswa.getValueAt(row, 5).toString();
            Date tgl = null;
            String tanggal_lahir = tabel_siswa.getValueAt(row, 6).toString();
            tgl = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(tanggal_lahir);
            hasil = crud.fotoSiswa(id);
            while (hasil.next()) {
                crud.setFoto(hasil.getString("foto"));
            }
            String foto = crud.getFoto();
            String path = new File(".").getCanonicalPath();
            System.out.println(path);
            System.out.println(foto);
            BufferedImage img = null;
            img = ImageIO.read(new File(path + "/img/siswa/" + foto));
            System.out.println(img);
            Image imagedResized = img.getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(imagedResized);
            label_photo.setText(null);
            label_photo.setIcon(imageIcon);
            txt_id.setText(String.valueOf(id));
            txt_nis.setText(String.valueOf(nis));
            txt_nama.setText(String.valueOf(nama));
            combobox_kelas.setSelectedItem(kelas);
            txt_namaPhoto.setText(foto);
            txt_namaPhoto.show();
            if ("L".equals(kelamin)) {
                radio_L.setSelected(true);
            } else if ("P".equals(kelamin)) {
                radio_P.setSelected(true);
            }
            txt_alamat.setText(String.valueOf(alamat));
            txt_tanggal.setDate(tgl);

        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_tabel_siswaMouseClicked

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nisActionPerformed

    private void label_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_photoMouseClicked
        jfc = new JFileChooser();
        if (jfc.showOpenDialog(label_photo) == JFileChooser.APPROVE_OPTION) {

            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image image = toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized = image.getScaledInstance(150, 200, Image.SCALE_DEFAULT);
            ImageIcon imageIcon = new ImageIcon(imagedResized);
            label_photo.setText(null);
            label_photo.setIcon(imageIcon);
            txt_namaPhoto.setText(jfc.getSelectedFile().getName());
            txt_namaPhoto.show();
            file = new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_label_photoMouseClicked

    private void txt_namaPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPhotoActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        Object[] baris = {"ID", "NIS", "Nama", "kelas", "kelamin", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_siswa.setModel(tabmode);
        try {
            crud.setKeyword(txt_cari.getText());
            hasil = crud.searchData(crud.getKeyword());

            while (hasil.next()) {
                crud.setID(hasil.getString("siswa_id"));
                crud.setNis(hasil.getInt("nis"));
                crud.setNama(hasil.getString("nama"));
                crud.setKelas(hasil.getInt("kelas"));
                crud.setKelamin(hasil.getString("kelamin"));
                crud.setAlamat(hasil.getString("alamat"));
                crud.setTanggal_Lahir(hasil.getDate("tanggal_lahir"));
                String tgl = crud.getTanggal_Lahir().toString();
                String nis = String.valueOf(crud.getNis());
                String kelas = String.valueOf(crud.getKelas());
                String[] data = {crud.getID(), nis, crud.getNama(), kelas, crud.getKelamin(), crud.getAlamat(), tgl};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        Object[] baris = {"ID", "NIS", "Nama", "kelas", "kelamin", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_siswa.setModel(tabmode);
        try {
            crud.setKeyword(txt_cari.getText());
            hasil = crud.searchData(crud.getKeyword());

            while (hasil.next()) {
                crud.setID(hasil.getString("siswa_id"));
                crud.setNis(hasil.getInt("nis"));
                crud.setNama(hasil.getString("nama"));
                crud.setKelas(hasil.getInt("kelas"));
                crud.setKelamin(hasil.getString("kelamin"));
                crud.setAlamat(hasil.getString("alamat"));
                crud.setTanggal_Lahir(hasil.getDate("tanggal_lahir"));
                String tgl = crud.getTanggal_Lahir().toString();
                String nis = String.valueOf(crud.getNis());
                String kelas = String.valueOf(crud.getKelas());
                String[] data = {crud.getID(), nis, crud.getNama(), kelas, crud.getKelamin(), crud.getAlamat(), tgl};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txt_cariCaretUpdate

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if (txt_id.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID belum diisi !");
            txt_id.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ? ", "  Warning", 2) == JOptionPane.YES_OPTION) {
                String id = "";
                try {
                    crud.setID(txt_id.getText());
                    crud.hapusData(crud.getID());
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void menu_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keluarMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?", "Warning", 2)
                == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menu_keluarMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked

    }//GEN-LAST:event_menuMouseClicked

    private void menu_ruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ruangActionPerformed
        this.dispose();
        Ruang_Form rf = new Ruang_Form();
        rf.show();
    }//GEN-LAST:event_menu_ruangActionPerformed

    private void menu_jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jadwalActionPerformed
        this.dispose();
        jadwal_form jf = new jadwal_form();
        jf.show();
    }//GEN-LAST:event_menu_jadwalActionPerformed

    private void menu_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_kelasActionPerformed
        this.dispose();
        Kelas_Form kf = new Kelas_Form();
        kf.show();
    }//GEN-LAST:event_menu_kelasActionPerformed

    private void menu_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guruActionPerformed
        this.dispose();
        Guru_Form gf = new Guru_Form();
        gf.show();
    }//GEN-LAST:event_menu_guruActionPerformed

    private void menu_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_siswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Session s = new Session();
                if (!s.getLogin()) {
                    new Siswa_Form().dispose();
                    Login_Form lf = new Login_Form();
                    lf.show();

                } else {
                    new Siswa_Form().setVisible(true);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combobox_kelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_photo;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menu_guru;
    private javax.swing.JMenuItem menu_jadwal;
    private javax.swing.JMenuItem menu_kelas;
    private javax.swing.JMenu menu_keluar;
    private javax.swing.JMenuItem menu_ruang;
    private javax.swing.JMenuItem menu_siswa;
    private javax.swing.JPanel panel_siswa;
    private javax.swing.JRadioButton radio_L;
    private javax.swing.JRadioButton radio_P;
    private javax.swing.JTable tabel_siswa;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_namaPhoto;
    private javax.swing.JTextField txt_nis;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
